[programs.devnet]
sns = "9hLY9Xj5C4e2szcEZDtn7mXLm7kAXJXBSoUF1FsKLtM6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mahesh/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
